// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Google Analytics Exporter API
//
//	The GA Exporter API makes use of the [Core Reporting API version
//	3.0](https://developers.google.com/analytics/devguides/reporting/core/v3/reference)
//	to access information about visitors to a web property. It pulls data from
//	an existing and preconfigured
//	[reporting view](https://support.google.com/analytics/answer/2649553?hl=en)
//	in a Google Analytics account.
//
//	# Errors
//	The API uses standard HTTP status codes to indicate the success or failure
//	of the API call. The body of the response will be JSON in the following
//	format:
//	```
//	{
//	  "code": 405,
//	  "message": "method POST is not allowed, but [GET] are"
//	}
//	```
//
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 0.0.1
//	Contact: Ga Exporter API mantainers<contact@quintsys.com> https://github.com/quintsys/ga-exporter
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
