// Code generated by go-swagger; DO NOT EDIT.

package visitors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// VisitorListHandlerFunc turns a function with the right signature into a visitor list handler
type VisitorListHandlerFunc func(VisitorListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn VisitorListHandlerFunc) Handle(params VisitorListParams) middleware.Responder {
	return fn(params)
}

// VisitorListHandler interface for that can handle valid visitor list params
type VisitorListHandler interface {
	Handle(VisitorListParams) middleware.Responder
}

// NewVisitorList creates a new http.Handler for the visitor list operation
func NewVisitorList(ctx *middleware.Context, handler VisitorListHandler) *VisitorList {
	return &VisitorList{Context: ctx, Handler: handler}
}

/*
	VisitorList swagger:route GET / Visitors visitorList

VisitorList visitor list API
*/
type VisitorList struct {
	Context *middleware.Context
	Handler VisitorListHandler
}

func (o *VisitorList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewVisitorListParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
