// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ErrorServiceUnavailable error service unavailable
//
// swagger:model error_service_unavailable
type ErrorServiceUnavailable struct {

	// code
	// Example: 503
	Code int64 `json:"code,omitempty"`

	// message
	// Example: service is not available
	Message string `json:"message,omitempty"`
}

// Validate validates this error service unavailable
func (m *ErrorServiceUnavailable) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this error service unavailable based on context it is used
func (m *ErrorServiceUnavailable) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ErrorServiceUnavailable) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErrorServiceUnavailable) UnmarshalBinary(b []byte) error {
	var res ErrorServiceUnavailable
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
