// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ErrorMethodNotAllowed error method not allowed
//
// swagger:model error_method_not_allowed
type ErrorMethodNotAllowed struct {

	// code
	// Example: 405
	Code int64 `json:"code,omitempty"`

	// message
	// Example: method POST is not allowed, but [GET] are
	Message string `json:"message,omitempty"`
}

// Validate validates this error method not allowed
func (m *ErrorMethodNotAllowed) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this error method not allowed based on context it is used
func (m *ErrorMethodNotAllowed) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ErrorMethodNotAllowed) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErrorMethodNotAllowed) UnmarshalBinary(b []byte) error {
	var res ErrorMethodNotAllowed
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
